apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    name: authentik-credentials
  data:
    - secretKey: password
      remoteRef:
        key: authentik/password
    - secretKey: username
      remoteRef:
        key: authentik/username
    - secretKey: encryption-key
      remoteRef:
        key: authentik/secret-key
    - secretKey: resend-key
      remoteRef:
        key: authentik/resend-key

