apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: geoip-license-key
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    name: geoip-license-key
  data:
  - secretKey: password
    remoteRef:
      key: authentik/geoip-license-key
  - secretKey: accountid
    remoteRef:
      key: authentik/geoip-account-id
