apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-csi-credentials
  namespace: truenas-csi
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: truenas-csi-credentials
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: truenas-csi-credentials
        property: password
