apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-widget-secrets
  namespace: glance
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: glance-widget-secrets
    creationPolicy: Owner
  data:
    - secretKey: CF_ACCOUNT_ID
      remoteRef:
        key: cloudflare/AccountTag
    - secretKey: CF_TUNNEL_ID
      remoteRef:
        key: cloudflare/tunnel/TunnelID
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: cloudflare/cert-manager/apikey
    - secretKey: TAUTULLI_API_KEY
      remoteRef:
        key: glance/TAUTULLI_API_KEY
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: glance/TRUENAS_API_KEY
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: glance/UNIFI_API_KEY
    - secretKey: ADGUARD_USERNAME
      remoteRef:
        key: adguard/username
    - secretKey: ADGUARD_PASSWORD
      remoteRef:
        key: adguard/password
