apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: dockerhub-token
spec:
  externalSecretName: dockerhub-token
  refreshTime: 1m
  namespaceSelectors:
    - matchLabels: {}
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: infisical
      kind: ClusterSecretStore
    target:
      name: dockerhub-token
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: '{{ `{{ dict "auths" (dict "https://index.docker.io/v1/" (dict "username" .username "password" .password "email" .email "auth" (printf "%s:%s" .username .password | b64enc))) | toJson }}` }}'
    data:
      - secretKey: password
        remoteRef:
          key: dockerhub/token
      - secretKey: email
        remoteRef:
          key: dockerhub/email
      - secretKey: username
        remoteRef:
          key: dockerhub/username