apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: dockerhub-token
spec:
  externalSecretName: dockerhub-token
  refreshTime: 1m
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - 1password
            - adguard-sync
            - cloudflare
            - duplicati
            - envoy-gateway-system
            - glance
            - home-assistant
            - infisical
            - inteldeviceplugins-system
            - joplin
            - opentelemetry
            - recipes
            - redis
            - victoria-metrics
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: infisical
      kind: ClusterSecretStore
    target:
      name: dockerhub-token
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: '{{ `{{ dict "auths" (dict "https://index.docker.io/v1/" (dict "username" .username "password" .password "email" .email "auth" (printf "%s:%s" .username .password | b64enc))) | toJson }}` }}'
    data:
      - secretKey: password
        remoteRef:
          key: dockerhub/token
      - secretKey: email
        remoteRef:
          key: dockerhub/email
      - secretKey: username
        remoteRef:
          key: dockerhub/username