apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-universal-auth
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: infisical-universal-auth
  data:
    - secretKey: client-id
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None
        key: infisical-eso-universal-auth
        property: client-id
        decodingStrategy: None
    - secretKey: client-secret
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None
        key: infisical-eso-universal-auth
        property: client-secret
        decodingStrategy: None