apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    infisical:
      hostAPI: {{ .Values.infisical.hostAPI | quote }}
      auth:
        universalAuthCredentials:
          clientId:
            name: {{ .Values.infisical.authSecret.name }}
            key: {{ .Values.infisical.authSecret.clientIdKey }}
            namespace: {{ .Release.Namespace }}
          clientSecret:
            name: {{ .Values.infisical.authSecret.name }}
            key: {{ .Values.infisical.authSecret.clientSecretKey }}
            namespace: {{ .Release.Namespace }}
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug | quote }}
        environmentSlug: {{ .Values.infisical.environmentSlug | quote }}
        secretsPath: {{ .Values.infisical.secretsPath | quote }}
        recursive: {{ .Values.infisical.recursive }}