apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config-pvc.yaml
  - nfs.yaml
  - service.yaml
  - deployment.yaml
  - cnp.yaml
  - duplicati-credentials.yaml
  - dockerhub-token.yaml
  - http-route.yaml
  - referencegrant.yaml

commonLabels:
  app: duplicati
  component: duplicati-app

namespace: duplicati

images:
  - name: linuxserver/duplicati
    newTag: "2.4.0"
