apiVersion: v2
name: envoy-gateway-system
description: Envoy Gateway controller chart and Gateway API configuration
version: 0.1.0
type: application
dependencies:
  - name: gateway-helm
    version: v1.9.2
    repository: oci://docker.io/envoyproxy
