apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-credentials
  namespace: adguard-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    name: adguard-credentials
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None
        key: adguard/password
        decodingStrategy: None
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None
        key: adguard/username
        decodingStrategy: None
