apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-credentials
  namespace: joplin
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: joplin-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: database-joplin/DB_PASSWORD
    - secretKey: username
      remoteRef:
        key: database-joplin/DB_USERNAME
    - secretKey: resend-apikey
      remoteRef:
        key: joplin/resend-apikey
