apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tibiary-api-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tibiary-credentials
    creationPolicy: Owner
    template:
      data:
        DB_CONNECTION_STRING: "postgresql://{{ .db_username }}:{{ .db_password }}@pgsql.nullservers.com:5432/tibiary?sslmode=disable"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        RESEND_APIKEY: "{{ .RESEND_APIKEY }}"
  data:
    - secretKey: db_username
      remoteRef:
        key: database-tibiary/DB_USERNAME
    - secretKey: db_password
      remoteRef:
        key: database-tibiary/DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: tibiary/JWT_SECRET
    - secretKey: RESEND_APIKEY
      remoteRef:
        key: tibiary/RESEND_APIKEY
