apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: mongo-credentials
    template:
      data:
        mongo_uri: "mongodb://{{ .username }}:{{ .password }}@mongodb.nullservers.com:27017/statistics"
  data:
    - secretKey: username
      remoteRef:
        key: tibia-statistics/username
    - secretKey: password
      remoteRef:
        key: tibia-statistics/password
