apiVersion: v1
kind: Service
metadata:
  name: bunkerweb-internal
  namespace: bunkerweb
  labels:
    helm.sh/chart: bunkerweb-1.0.16
    app.kubernetes.io/name: bunkerweb
    app.kubernetes.io/instance: bunkerweb
    app.kubernetes.io/version: "1.6.9"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    bunkerweb.io/component: "bunkerweb"
  clusterIP: None
