apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bunkerweb-credentials
  namespace: bunkerweb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: bunkerweb-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        database-uri: "mysql://{{.dbUsername}}:{{.dbPassword}}@mariadb.nullservers.com:3306/bunkerweb"
        admin-username: "{{ .username }}"
        admin-password: "{{ .password }}"
        mariadb-user: "{{ .dbUsername }}"
        mariadb-password: "{{ .dbPassword }}"
        api-token: "{{ .token }}"
        flask-secret: "{{ .flask }}"
        totp-secret: "{{ .otp }}"
  data:
    - secretKey: username
      remoteRef:
        key: bunkerweb-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: bunkerweb-credentials
        property: password
    - secretKey: dbPassword
      remoteRef:
        key: bunkerweb-credentials
        property: dbPassword
    - secretKey: dbUsername
      remoteRef:
        key: bunkerweb-credentials
        property: dbUsername
    - secretKey: token
      remoteRef:
        key: bunkerweb-credentials
        property: token
    - secretKey: flask
      remoteRef:
        key: bunkerweb-credentials
        property: flask
    - secretKey: otp
      remoteRef:
        key: bunkerweb-credentials
        property: otp
