apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password
  namespace: recipes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    name: recipes-db-pwd
  data:
    - secretKey: password
      remoteRef:
        key: database-recipes/DB_PASSWORD
    - secretKey: username
      remoteRef:
        key: database-recipes/DB_USERNAME
    - secretKey: secret-key
      remoteRef:
        key: recipes/secret-key
    - secretKey: email-api-key
      remoteRef:
        key: recipes/resend-apikey
