apiVersion: batch/v1
kind: CronJob
metadata:
  name: tibia-statistics
spec:
  schedule: "0 12,23 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: tibia-statistics
        spec:
          imagePullSecrets:
            - name: gh-docker-pat
          containers:
            - name: tibia-statistics
              image: ghcr.io/andrebovendorp/tibia-statistics:latest
              imagePullPolicy: Always
              env:
                - name: DB_TYPE
                  value: mongodb
                - name: API_BASE_URL
                  value: http://tibiadata-api-go:8080
                - name: MONGO_DB_HOST
                  value: mongodb.nullservers.com
                - name: MONGO_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: tibia-statistics-mongo-credentials
                      key: password
                - name: MONGO_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: tibia-statistics-mongo-credentials
                      key: username
                - name: MONGO_DB_NAME
                  value: statistics
          restartPolicy: OnFailure
