apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cronjob.yaml
  - tibiadata-api-go-deployment.yaml
  - tibiadata-api-go-service.yaml
  - cnp.yaml
  - tibia-statistics-egress-cnp.yaml
  - tibiadata-api-go-egress-cnp.yaml
  - github-token.yaml
  - tibia-statistics-mongo-credentials.yaml

commonLabels:
  app: tibia-statistics
  component: tibia-statistics

namespace: tibia-statistics

images:
  - name: ghcr.io/andrebovendorp/tibia-statistics
    newTag: latest
  - name: ghcr.io/andrebovendorp/tibiadata-api-go
    newTag: latest
