apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tibia-statistics-mongo-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: tibia-statistics-mongo-credentials
  data:
    - secretKey: username
      remoteRef:
        key: tibia-statistics/username
    - secretKey: password
      remoteRef:
        key: tibia-statistics/password
