# ExternalSecret to materialize a pull secret for the private GitLab container registry
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: workspace-private-auth
  namespace: tibiary
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: gitlab-pat
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "registry.gitlab.com": {
                "username": "{{ .username }}",
                "password": "{{ .password }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: gitlab/username
    - secretKey: password
      remoteRef:
        key: tibiary/GITLAB_PAT
