apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    name: grafana-oauth-credentials
  data:
  - secretKey: client-id
    remoteRef:
      key: grafana/client-id
  - secretKey: client-secret
    remoteRef:
      key: grafana/client-secret
