---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgsql-password-infisical
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    name: immich-credentials-infisical
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None
        key: database-immich/DB_PASSWORD
        decodingStrategy: None
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None
        key: database-immich/DB_USERNAME
        decodingStrategy: None
    - secretKey: HF_TOKEN
      remoteRef:
        conversionStrategy: Default
        metadataPolicy: None
        key: database-immich/HF_TOKEN
        decodingStrategy: None
