apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    name: cloudflare-tunnel-token
    template:
      data:
        credentials.json: '{{ dict "AccountTag" .AccountTag "TunnelSecret" .TunnelSecret "TunnelID" .TunnelID | toJson }}'
  data:
    - secretKey: AccountTag
      remoteRef:
        key: cloudflare/AccountTag
    - secretKey: TunnelSecret
      remoteRef:
        key: cloudflare/tunnel/TunnelSecret
    - secretKey: TunnelID
      remoteRef:
        key: cloudflare/tunnel/TunnelID
